server:
  port: 9001
  servlet:
    context-path: /hzh-web

spring:
  datasource:
    url: jdbc:mysql://192.168.79.131:3306/hzh_sts?useOldAliasMetadataBehavior=true&useSSL=false&serverTimezone=GMT
    username: root
    password: 5q6W7e8R

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#是否激活 swagger true or false
swagger:
  enable: true

